### ISSUE TITLE
AttributeError: module 'dearpygui.dearpygui' has no attribute 'add_item_double_clicked_handler'

### ISSUE THREAD

**Issue by liudonghua123** [JiauZhang/DragGAN#18]
I installed dearpygui and cloned this repo. I tried to execute `python gui.py`. Then the following errors appeared.

```
D:\code\python\DragGAN>python gui.py
Traceback (most recent call last):
  File "D:\code\python\DragGAN\gui.py", line 183, in <module>
    dpg.add_item_double_clicked_handler(callback=select_point)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'dearpygui.dearpygui' has no attribute 'add_item_double_clicked_handler'

D:\code\python\DragGAN>python
Python 3.11.2 (878ead1-dirty:878ead1, Feb 13 2023, 05:29:50) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dearpygui
>>> import dearpygui.dearpygui
>>> import dearpygui.dearpygui as dpg
>>> dpg.add_item_double_clicked_handler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dearpygui.dearpygui' has no attribute 'add_item_double_clicked_handler'
>>> dearpygui.__version__
'1.8.0'
>>>

```

**Comment by liudonghua123** [comment]
I fixed this via update dearpygui.

```
C:\Users\Liu.D.H>pip install dearpygui -U
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: dearpygui in c:\users\liu.d.h\appdata\local\programs\python\python311\lib\site-packages (1.8.0)
Collecting dearpygui
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/27/06/e47e87fb6bab117b7ce2a70516d943e380cb855eac4665b7d7eef8479d1f/dearpygui-1.9.1-cp311-cp311-win_amd64.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 3.3 MB/s eta 0:00:00
Installing collected packages: dearpygui
  Attempting uninstall: dearpygui
    Found existing installation: dearpygui 1.8.0
    Uninstalling dearpygui-1.8.0:
      Successfully uninstalled dearpygui-1.8.0
Successfully installed dearpygui-1.9.1

C:\Users\Liu.D.H>
```
